"""Typer CLI: ``fluxlit dev``, ``run``, ``shutdown``, ``doctor``, ``build``, ``new``.

The ``fluxlit`` setuptools entrypoint calls :func:`main`. Commands resolve defaults from
:func:`fluxlit.config.load_project_config` and :class:`~fluxlit.config.FluxlitSettings`.
"""

from __future__ import annotations

import json
import os
import platform
import socket
import sys
from pathlib import Path
from typing import Annotated, Literal
from urllib.parse import urlparse

import typer

from fluxlit.config import load_project_config, resolve_binding, resolve_target
from fluxlit.runtime import run_unified, shutdown_unified_process

app = typer.Typer(no_args_is_help=True, add_completion=False)

CheckStatus = Literal["PASS", "WARN", "FAIL"]


def _fluxlit_auth_env_present() -> bool:
    """True when JWT/OIDC-related ``FLUXLIT_*`` variables look configured."""
    prefixes = ("FLUXLIT_JWT_", "FLUXLIT_OIDC_")
    for key, val in os.environ.items():
        if any(key.startswith(p) for p in prefixes) and (val or "").strip():
            return True
    return False


def _dockerfile_body(target: str) -> str:
    # Digest for python:3.12-slim (supply-chain pin); bump when rebuilding base images.
    _py_slim_digest = "sha256:ec948fa5f90f4f8907e89f4800cfd2d2e91e391a4bce4a6afa77ba265bc3a2fe"
    return (
        "# Generated by `fluxlit build` — adjust COPY/RUN for your app layout.\n"
        f"# python:3.12-slim @ {_py_slim_digest}\n"
        f"FROM python@{_py_slim_digest}\n"
        "WORKDIR /app\n"
        'RUN pip install --no-cache-dir "fluxlit>=0.5.0"\n'
        "COPY . .\n"
        "RUN useradd --create-home --uid 1000 appuser \\\n"
        "    && chown -R appuser:appuser /app\n"
        "USER appuser\n"
        "ENV FLUXLIT_GATEWAY_HOST=0.0.0.0\n"
        "EXPOSE 8000\n"
        f'CMD ["fluxlit", "run", "{target}"]\n'
    )


def _dockerignore_body() -> str:
    return (
        "__pycache__\n"
        "*.py[cod]\n"
        ".git\n"
        ".venv\n"
        "venv\n"
        ".pytest_cache\n"
        ".mypy_cache\n"
        ".ruff_cache\n"
        "*.egg-info\n"
        "dist\n"
        "build\n"
        ".env\n"
    )


def _scaffold_app_body(profile: Literal["minimal", "auth-ready", "deploy"]) -> str:
    if profile == "auth-ready":
        return '''"""FluxLit auth-ready demo app.

Install auth helpers with: pip install "fluxlit[auth]"
"""

from fluxlit import FluxLit

app = FluxLit(title="FluxLit Auth Demo")


@app.api.get("/public")
def public():
    return {"message": "public"}


@app.page("/")
def home(st, client):
    st.title("Auth-ready Dashboard")
    st.write(client.get("/public").json())
    st.info("Add app.make_jwt_bearer() or app.attach_oidc_login(...) when ready.")


if __name__ == "__main__":
    import subprocess
    import sys

    subprocess.run([sys.executable, "-m", "fluxlit", "dev"], check=True)
'''
    if profile == "deploy":
        return '''"""FluxLit deployment-ready starter."""

from fluxlit import FluxLit

app = FluxLit(
    title="FluxLit Deploy Demo",
    streamlit_page_config={"layout": "wide"},
)


@app.api.get("/items")
def items():
    return [{"name": "Ada"}, {"name": "Grace"}]


@app.page("/")
def home(st, client):
    st.title("Deployment Dashboard")
    st.write(client.get("/items").json())
    st.caption("Run `fluxlit doctor` before deploying behind a proxy.")


if __name__ == "__main__":
    import subprocess
    import sys

    subprocess.run([sys.executable, "-m", "fluxlit", "dev"], check=True)
'''
    return '''"""FluxLit demo app."""

from fluxlit import FluxLit

app = FluxLit(title="FluxLit Demo")


@app.api.get("/users")
def users():
    return [{"name": "Ada"}]


@app.page("/")
def home(st, client):
    st.title("Dashboard")
    r = client.get("/users")
    st.write(r.json())


if __name__ == "__main__":
    import subprocess
    import sys

    subprocess.run([sys.executable, "-m", "fluxlit", "dev"], check=True)
'''


def _tcp_url_reachable(url: str, *, timeout_s: float = 0.25) -> tuple[bool, str]:
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        return False, "not a valid http(s) URL"
    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    try:
        with socket.create_connection((parsed.hostname, port), timeout=timeout_s):
            return True, f"{parsed.hostname}:{port} reachable"
    except OSError as exc:
        return False, f"{parsed.hostname}:{port} unreachable ({exc})"


@app.command()
def dev(
    target: str | None = typer.Argument(
        default=None,
        help="Import path to your FluxLit instance (default: from fluxlit.toml or app:app).",
    ),
    host: str | None = typer.Option(None, help="Bind address for the unified gateway."),
    port: int | None = typer.Option(None, help="Port for the unified gateway."),
    log_level: str | None = typer.Option(
        None, help="Uvicorn log level (debug, info, warning, error)."
    ),
    proxy_headers: bool = typer.Option(False, help="Trust X-Forwarded-* headers from a proxy."),
    forwarded_allow_ips: str | None = typer.Option(
        None,
        help="Comma-separated IPs to trust for forwarded headers (uvicorn forwarded_allow_ips).",
    ),
    reload: bool = typer.Option(
        False,
        help="Reload on code changes; use --reload-scope for gateway-only vs full stack.",
    ),
    reload_scope: str = typer.Option(
        "gateway",
        "--reload-scope",
        help="'gateway' reloads the ASGI app only; 'full' also restarts Streamlit on file changes.",
    ),
    pidfile: Annotated[
        Path | None,
        typer.Option(
            "--pidfile",
            help="Where to write the PID file (default: .fluxlit-dev.pid or FLUXLIT_PIDFILE).",
        ),
    ] = None,
    no_pidfile: bool = typer.Option(
        False,
        "--no-pidfile",
        help="Do not write a PID file (also respect FLUXLIT_NO_PIDFILE=1).",
    ),
) -> None:
    """Run the unified stack for local development (Streamlit subprocess + Uvicorn gateway).

    Resolves ``target``, bind address, port, and log level from CLI, project file, and
    :class:`~fluxlit.config.FluxlitSettings`. See :func:`fluxlit.runtime.run_unified`.
    """
    if reload and reload_scope not in {"gateway", "full"}:
        typer.echo(
            "--reload-scope must be 'gateway' or 'full'.",
            err=True,
        )
        raise typer.Exit(code=2)

    from fluxlit.runtime import load_fluxlit

    pc = load_project_config()
    resolved_target = resolve_target(target, pc)
    fl = load_fluxlit(resolved_target)
    host_r, port_r, log_r = resolve_binding(
        cli_host=host,
        cli_port=port,
        cli_log_level=log_level,
        pc=pc,
        settings_gateway_host=fl.settings.gateway_host,
        settings_gateway_port=fl.settings.gateway_port,
        settings_log_level=fl.settings.log_level,
    )
    run_unified(
        resolved_target,
        host=host_r,
        port=port_r,
        reload=reload,
        reload_scope=reload_scope,
        log_level=log_r,
        proxy_headers=proxy_headers,
        forwarded_allow_ips=forwarded_allow_ips,
        pidfile=pidfile,
        write_pidfile=not no_pidfile,
    )


@app.command()
def shutdown(
    pidfile: Annotated[
        Path | None,
        typer.Option(
            "--pidfile",
            help="PID file path (default: .fluxlit-dev.pid in cwd or FLUXLIT_PIDFILE).",
        ),
    ] = None,
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="After wait, send SIGKILL (POSIX only) if still running.",
    ),
    wait_s: float = typer.Option(
        5.0,
        "--wait",
        help="Seconds to wait after SIGTERM before --force kicks in.",
    ),
) -> None:
    """Stop ``fluxlit dev`` or ``fluxlit run`` using the PID file they write.

    Run this from the same working directory (or pass ``--pidfile`` / set ``FLUXLIT_PIDFILE``)
    as the server process. Normal exit removes the PID file; this command also deletes it when
    the process is already gone.
    """
    code, msg = shutdown_unified_process(pidfile, force=force, wait_s=wait_s)
    typer.echo(msg)
    raise typer.Exit(code=code)


@app.command("run")
def run_cmd(
    target: str | None = typer.Argument(
        default=None,
        help="Import path to your FluxLit instance (default: from fluxlit.toml or app:app).",
    ),
    host: str | None = typer.Option(None, help="Bind address for the unified gateway."),
    port: int | None = typer.Option(None, help="Port for the unified gateway."),
    log_level: str | None = typer.Option(
        None, help="Uvicorn log level (debug, info, warning, error)."
    ),
    proxy_headers: bool = typer.Option(False, help="Trust X-Forwarded-* headers from a proxy."),
    forwarded_allow_ips: str | None = typer.Option(
        None,
        help="Comma-separated IPs to trust for forwarded headers (uvicorn forwarded_allow_ips).",
    ),
    pidfile: Annotated[
        Path | None,
        typer.Option(
            "--pidfile",
            help="Where to write the PID file (default: .fluxlit-dev.pid or FLUXLIT_PIDFILE).",
        ),
    ] = None,
    no_pidfile: bool = typer.Option(
        False,
        "--no-pidfile",
        help="Do not write a PID file (also respect FLUXLIT_NO_PIDFILE=1).",
    ),
) -> None:
    """Run the unified stack for production-style use (no Uvicorn reload).

    Same resolution rules as :func:`dev`; always calls :func:`fluxlit.runtime.run_unified`
    with ``reload=False``.
    """
    from fluxlit.runtime import load_fluxlit

    pc = load_project_config()
    resolved_target = resolve_target(target, pc)
    fl = load_fluxlit(resolved_target)
    host_r, port_r, log_r = resolve_binding(
        cli_host=host,
        cli_port=port,
        cli_log_level=log_level,
        pc=pc,
        settings_gateway_host=fl.settings.gateway_host,
        settings_gateway_port=fl.settings.gateway_port,
        settings_log_level=fl.settings.log_level,
    )
    run_unified(
        resolved_target,
        host=host_r,
        port=port_r,
        reload=False,
        log_level=log_r,
        proxy_headers=proxy_headers,
        forwarded_allow_ips=forwarded_allow_ips,
        pidfile=pidfile,
        write_pidfile=not no_pidfile,
    )


def _doctor_checks(target: str) -> list[tuple[str, CheckStatus, str]]:
    """Run static checks; each row is ``(name, PASS|WARN|FAIL, message)``."""
    from fluxlit.runtime import load_fluxlit
    from fluxlit.runtime.import_target import import_target_candidates

    rows: list[tuple[str, CheckStatus, str]] = []

    rows.append(("python_version", "PASS", platform.python_version()))
    sys_path_head = ", ".join((p or ".") for p in sys.path[:3])
    rows.append(("sys_path_head", "PASS", sys_path_head or "(empty)"))

    fl = None
    mod_name = target.partition(":")[0]
    candidates = import_target_candidates(mod_name)
    if len(candidates) > 1:
        shown = ", ".join(str(p) for p in candidates[:4])
        more = f" (+{len(candidates) - 4} more)" if len(candidates) > 4 else ""
        rows.append(
            (
                "import_shadowing",
                "WARN",
                f"multiple import candidates for {mod_name!r}: {shown}{more}; "
                "run from the intended project root or trim PYTHONPATH",
            )
        )
    elif candidates:
        rows.append(("import_shadowing", "PASS", f"{mod_name!r} resolves from {candidates[0]}"))
    else:
        rows.append(
            ("import_shadowing", "PASS", f"no top-level file/package candidates for {mod_name!r}")
        )

    try:
        fl = load_fluxlit(target)
        rows.append(("import_target", "PASS", target))
    except Exception as e:
        rows.append(("import_target", "FAIL", str(e)))

    try:
        import fastapi  # noqa: F401
        import httpx  # noqa: F401
        import streamlit  # noqa: F401
        import uvicorn  # noqa: F401
    except ImportError as e:
        rows.append(("dependencies", "FAIL", str(e)))
    else:
        rows.append(("dependencies", "PASS", "fastapi, streamlit, uvicorn, httpx importable"))

    try:
        import streamlit as st

        parts = st.__version__.split(".")
        major, minor = int(parts[0]), int(parts[1])
        if (major, minor) < (1, 33):
            rows.append(
                (
                    "streamlit_version",
                    "WARN",
                    f"{st.__version__} (fluxlit declares streamlit>=1.36; upgrade recommended)",
                )
            )
        else:
            rows.append(("streamlit_version", "PASS", st.__version__))
    except Exception as e:
        rows.append(("streamlit_version", "WARN", str(e)))

    if fl is not None:
        pc = load_project_config()
        host, port, _ = resolve_binding(
            cli_host=None,
            cli_port=None,
            cli_log_level=None,
            pc=pc,
            settings_gateway_host=fl.settings.gateway_host,
            settings_gateway_port=fl.settings.gateway_port,
            settings_log_level=fl.settings.log_level,
        )
        bind_host = "127.0.0.1" if host in {"0.0.0.0", ""} else host
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                s.bind((bind_host, port))
            rows.append(("gateway_bind", "PASS", f"{host}:{port} is available"))
        except OSError as e:
            rows.append(("gateway_bind", "FAIL", str(e)))

    internal = os.environ.get("FLUXLIT_INTERNAL_API_BASE", "").strip()
    if internal:
        parsed = urlparse(internal)
        if not parsed.scheme or not parsed.netloc:
            rows.append(("FLUXLIT_INTERNAL_API_BASE", "FAIL", "not a valid absolute URL"))
        elif fl is not None:
            url_path = (parsed.path or "/").rstrip("/")
            expected = fl.settings.api_mount_path.rstrip("/")
            if url_path != expected:
                rows.append(
                    (
                        "FLUXLIT_INTERNAL_API_BASE",
                        "WARN",
                        f"path {url_path!r} should match api_mount_path {expected!r}",
                    )
                )
            else:
                rows.append(("FLUXLIT_INTERNAL_API_BASE", "PASS", "set and matches api_mount_path"))
        else:
            rows.append(
                (
                    "FLUXLIT_INTERNAL_API_BASE",
                    "PASS",
                    "set (import failed; path not compared to api_mount_path)",
                )
            )
    else:
        rows.append(
            (
                "FLUXLIT_INTERNAL_API_BASE",
                "PASS",
                "unset (normal when not inside Streamlit subprocess)",
            )
        )

    if _fluxlit_auth_env_present():
        rows.append(
            (
                "jwt_clock_skew",
                "WARN",
                "JWT/OIDC env detected — synchronize clocks (NTP); validation uses exp/nbf.",
            )
        )
    else:
        rows.append(
            (
                "jwt_clock_skew",
                "PASS",
                "no JWT/OIDC FLUXLIT_* env vars detected",
            )
        )

    if _fluxlit_auth_env_present():
        try:
            import jwt  # noqa: F401
        except ImportError:
            rows.append(
                (
                    "fluxlit_auth_extra",
                    "FAIL",
                    "JWT/OIDC env vars set but PyJWT is missing; pip install 'fluxlit[auth]'",
                )
            )
        else:
            rows.append(("fluxlit_auth_extra", "PASS", "PyJWT importable (fluxlit[auth])"))

    if (
        fl is not None
        and fl.settings.public_mount_path()
        and not fl.settings.public_base_url.strip()
    ):
        rows.append(
            (
                "oauth_public_base_url",
                "WARN",
                "subpath set but public_base_url empty — set FLUXLIT_PUBLIC_BASE_URL for correct "
                "OAuth redirect_uri behind a reverse proxy (see docs/configuration.html)",
            )
        )

    if fl is not None and fl.settings.public_mount_path():
        if fl.settings.trust_proxy:
            rows.append(
                (
                    "proxy_headers",
                    "PASS",
                    "trust_proxy enabled for subpath deployment",
                )
            )
        else:
            rows.append(
                (
                    "proxy_headers",
                    "WARN",
                    "subpath/root_path set but trust_proxy false — behind Posit Connect/nginx set "
                    "FLUXLIT_TRUST_PROXY=1 or pass --proxy-headers",
                )
            )

    if fl is not None and fl.settings.trust_proxy:
        allow = (fl.settings.forwarded_allow_ips or "").strip()
        if not allow or allow == "*":
            rows.append(
                (
                    "forwarded_allow_ips",
                    "WARN",
                    "trust_proxy enabled but forwarded_allow_ips is broad; set "
                    "FLUXLIT_FORWARDED_ALLOW_IPS to your proxy IP/CIDR in production",
                )
            )
        else:
            rows.append(("forwarded_allow_ips", "PASS", allow))

    if fl is not None and fl.settings.public_base_url.strip():
        parsed_public = urlparse(fl.settings.public_base_url.strip())
        root = fl.settings.public_mount_path().rstrip("/")
        public_path = (parsed_public.path or "").rstrip("/")
        if root and public_path and public_path != root:
            rows.append(
                (
                    "public_base_url",
                    "WARN",
                    f"path {public_path!r} does not match public mount {root!r}",
                )
            )
        elif not parsed_public.scheme or not parsed_public.netloc:
            rows.append(("public_base_url", "FAIL", "not a valid absolute URL"))
        else:
            rows.append(("public_base_url", "PASS", fl.settings.public_base_url.strip()))

    upstream_file = os.environ.get("FLUXLIT_STREAMLIT_UPSTREAM_FILE", "").strip()
    upstream_env = os.environ.get("FLUXLIT_STREAMLIT_UPSTREAM", "").strip()
    if upstream_file:
        fp = Path(upstream_file)
        if not fp.exists():
            rows.append(("streamlit_upstream_state", "FAIL", f"state file missing: {fp}"))
        else:
            raw = fp.read_text(encoding="utf-8").strip()
            if not raw:
                rows.append(("streamlit_upstream_state", "WARN", f"state file is empty: {fp}"))
            else:
                ok, msg = _tcp_url_reachable(raw)
                rows.append(("streamlit_upstream_state", "PASS" if ok else "WARN", msg))
    elif upstream_env:
        ok, msg = _tcp_url_reachable(upstream_env)
        rows.append(("streamlit_upstream", "PASS" if ok else "WARN", msg))

    cors_on = fl is not None and bool(fl.settings.cors_allow_origins)
    sec_off = fl is not None and not fl.settings.enable_security_headers
    if cors_on and sec_off:
        rows.append(
            (
                "security_headers",
                "WARN",
                "CORS on, security headers off — consider FLUXLIT_ENABLE_SECURITY_HEADERS=1",
            )
        )

    return rows


def _doctor_payload(
    rows: list[tuple[str, CheckStatus, str]],
    *,
    target: str,
    warnings_only: bool,
) -> dict[str, object]:
    has_fail = any(status == "FAIL" for _, status, _ in rows)
    has_warn = any(status == "WARN" for _, status, _ in rows)
    status = (
        "fail" if has_fail and not warnings_only else "warn" if has_fail or has_warn else "pass"
    )
    return {
        "status": status,
        "target": target,
        "warnings_only": warnings_only,
        "checks": [
            {"name": name, "status": check_status, "detail": detail}
            for name, check_status, detail in rows
        ],
    }


@app.command()
def doctor(
    target: str | None = typer.Argument(
        default=None,
        help="Import path to your FluxLit instance (default: from fluxlit.toml or app:app).",
    ),
    warnings_only: bool = typer.Option(
        False,
        "--warnings-only",
        help="Always exit 0 (still print FAIL lines).",
    ),
    json_output: bool = typer.Option(
        False,
        "--json",
        help="Emit machine-readable JSON instead of human-readable text.",
    ),
) -> None:
    """Print PASS/WARN/FAIL diagnostics (imports, deps, bind, env).

    Exits with code ``1`` if any check fails, unless ``--warnings-only`` is set.
    """
    pc = load_project_config()
    resolved_target = resolve_target(target, pc)

    rows = _doctor_checks(resolved_target)
    if json_output:
        typer.echo(
            json.dumps(_doctor_payload(rows, target=resolved_target, warnings_only=warnings_only))
        )
    else:
        typer.echo("FluxLit doctor")
        typer.echo("")
        for name, status, message in rows:
            typer.echo(f"{status:4}  {name}: {message}")
        typer.echo("")
    if not warnings_only and any(s == "FAIL" for _, s, _ in rows):
        raise typer.Exit(code=1)


@app.command()
def build(
    output: Annotated[
        Path | None,
        typer.Option(
            "--output",
            "-o",
            help="Directory for Dockerfile and .dockerignore (default: current directory).",
        ),
    ] = None,
    target: str | None = typer.Argument(
        default=None,
        help="Import path for CMD (default: from fluxlit.toml or app:app).",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing Dockerfile / .dockerignore.",
    ),
) -> None:
    """Emit a minimal ``Dockerfile`` and ``.dockerignore`` for container deployment.

    Refuses to overwrite existing files unless ``--force``. Adjust generated files for
    your layout (dependencies, non-root user, etc.).
    """
    pc = load_project_config()
    resolved_target = resolve_target(target, pc)
    out_dir = output or Path(".")
    out_dir.mkdir(parents=True, exist_ok=True)
    dockerfile = out_dir / "Dockerfile"
    dockerignore = out_dir / ".dockerignore"
    if not force:
        if dockerfile.exists() or dockerignore.exists():
            typer.echo(
                f"Refusing to overwrite {dockerfile} / {dockerignore} (use --force).",
                err=True,
            )
            raise typer.Exit(code=1)
    dockerfile.write_text(_dockerfile_body(resolved_target), encoding="utf-8")
    dockerignore.write_text(_dockerignore_body(), encoding="utf-8")
    typer.echo(f"Wrote {dockerfile} and {dockerignore}")


@app.command()
def new(
    name: str = typer.Argument(..., help="Project directory name."),
    profile: Literal["minimal", "auth-ready", "deploy"] = typer.Option(
        "minimal",
        "--profile",
        help="Scaffold profile: minimal, auth-ready, or deploy.",
    ),
) -> None:
    """Create ``<name>/app.py`` with a sample API route and Streamlit home page."""
    root = Path(name)
    if root.exists():
        typer.echo(f"Destination already exists: {root}", err=True)
        raise typer.Exit(code=1)
    root.mkdir(parents=True)
    (root / "fluxlit.toml").write_text(
        'target = "app:app"\ngateway_port = 8000\n',
        encoding="utf-8",
    )
    (root / "app.py").write_text(_scaffold_app_body(profile), encoding="utf-8")
    typer.echo(
        f"Created {name}/ ({profile}) — run: cd {name} && fluxlit dev  "
        f"(or: uvicorn app:app --reload --port 8000)"
    )


def main() -> None:
    """Invoke the root Typer application (console script entrypoint)."""
    app()
