"""Typer CLI: ``fluxlit dev``, ``run``, ``doctor``, ``build``, ``new``.

The ``fluxlit`` setuptools entrypoint calls :func:`main`. Commands resolve defaults from
:func:`fluxlit.project_config.load_project_config` and :class:`~fluxlit.config.FluxlitSettings`.
"""

from __future__ import annotations

import os
import platform
import socket
from pathlib import Path
from typing import Annotated, Literal
from urllib.parse import urlparse

import typer

from fluxlit.project_config import load_project_config, resolve_binding, resolve_target
from fluxlit.runtime import run_unified

app = typer.Typer(no_args_is_help=True, add_completion=False)

CheckStatus = Literal["PASS", "WARN", "FAIL"]


def _dockerfile_body(target: str) -> str:
    return (
        "# Generated by `fluxlit build` — adjust COPY/RUN for your app layout.\n"
        "FROM python:3.12-slim\n"
        "WORKDIR /app\n"
        'RUN pip install --no-cache-dir "fluxlit>=0.2"\n'
        "COPY . .\n"
        "ENV FLUXLIT_GATEWAY_HOST=0.0.0.0\n"
        "EXPOSE 8000\n"
        f'CMD ["fluxlit", "run", "{target}"]\n'
    )


def _dockerignore_body() -> str:
    return (
        "__pycache__\n"
        "*.py[cod]\n"
        ".git\n"
        ".venv\n"
        "venv\n"
        ".pytest_cache\n"
        ".mypy_cache\n"
        ".ruff_cache\n"
        "*.egg-info\n"
        "dist\n"
        "build\n"
        ".env\n"
    )


@app.command()
def dev(
    target: str | None = typer.Argument(
        default=None,
        help="Import path to your FluxLit instance (default: from fluxlit.toml or app:app).",
    ),
    host: str | None = typer.Option(None, help="Bind address for the unified gateway."),
    port: int | None = typer.Option(None, help="Port for the unified gateway."),
    log_level: str | None = typer.Option(
        None, help="Uvicorn log level (debug, info, warning, error)."
    ),
    proxy_headers: bool = typer.Option(False, help="Trust X-Forwarded-* headers from a proxy."),
    forwarded_allow_ips: str | None = typer.Option(
        None,
        help="Comma-separated IPs to trust for forwarded headers (uvicorn forwarded_allow_ips).",
    ),
    reload: bool = typer.Option(
        False,
        help="Reload the API gateway on code changes (Streamlit subprocess is not restarted).",
    ),
    reload_scope: str = typer.Option(
        "gateway",
        "--reload-scope",
        help="Only 'gateway' is supported: reloads the ASGI app, not Streamlit.",
    ),
) -> None:
    """Run the unified stack for local development (Streamlit subprocess + Uvicorn gateway).

    Resolves ``target``, bind address, port, and log level from CLI, project file, and
    :class:`~fluxlit.config.FluxlitSettings`. See :func:`fluxlit.runtime.run_unified`.
    """
    if reload and reload_scope != "gateway":
        typer.echo(
            "Only --reload-scope=gateway is supported (Streamlit never reloads).",
            err=True,
        )
        raise typer.Exit(code=2)

    from fluxlit.runtime import load_fluxlit

    pc = load_project_config()
    resolved_target = resolve_target(target, pc)
    fl = load_fluxlit(resolved_target)
    host_r, port_r, log_r = resolve_binding(
        cli_host=host,
        cli_port=port,
        cli_log_level=log_level,
        pc=pc,
        settings_gateway_host=fl.settings.gateway_host,
        settings_gateway_port=fl.settings.gateway_port,
        settings_log_level=fl.settings.log_level,
    )
    run_unified(
        resolved_target,
        host=host_r,
        port=port_r,
        reload=reload,
        log_level=log_r,
        proxy_headers=proxy_headers,
        forwarded_allow_ips=forwarded_allow_ips,
    )


@app.command("run")
def run_cmd(
    target: str | None = typer.Argument(
        default=None,
        help="Import path to your FluxLit instance (default: from fluxlit.toml or app:app).",
    ),
    host: str | None = typer.Option(None, help="Bind address for the unified gateway."),
    port: int | None = typer.Option(None, help="Port for the unified gateway."),
    log_level: str | None = typer.Option(
        None, help="Uvicorn log level (debug, info, warning, error)."
    ),
    proxy_headers: bool = typer.Option(False, help="Trust X-Forwarded-* headers from a proxy."),
    forwarded_allow_ips: str | None = typer.Option(
        None,
        help="Comma-separated IPs to trust for forwarded headers (uvicorn forwarded_allow_ips).",
    ),
) -> None:
    """Run the unified stack for production-style use (no Uvicorn reload).

    Same resolution rules as :func:`dev`; always calls :func:`fluxlit.runtime.run_unified`
    with ``reload=False``.
    """
    from fluxlit.runtime import load_fluxlit

    pc = load_project_config()
    resolved_target = resolve_target(target, pc)
    fl = load_fluxlit(resolved_target)
    host_r, port_r, log_r = resolve_binding(
        cli_host=host,
        cli_port=port,
        cli_log_level=log_level,
        pc=pc,
        settings_gateway_host=fl.settings.gateway_host,
        settings_gateway_port=fl.settings.gateway_port,
        settings_log_level=fl.settings.log_level,
    )
    run_unified(
        resolved_target,
        host=host_r,
        port=port_r,
        reload=False,
        log_level=log_r,
        proxy_headers=proxy_headers,
        forwarded_allow_ips=forwarded_allow_ips,
    )


def _doctor_checks(target: str) -> list[tuple[str, CheckStatus, str]]:
    """Run static checks; each row is ``(name, PASS|WARN|FAIL, message)``."""
    from fluxlit.runtime import load_fluxlit

    rows: list[tuple[str, CheckStatus, str]] = []

    rows.append(("python_version", "PASS", platform.python_version()))

    fl = None
    try:
        fl = load_fluxlit(target)
        rows.append(("import_target", "PASS", target))
    except Exception as e:
        rows.append(("import_target", "FAIL", str(e)))

    try:
        import fastapi  # noqa: F401
        import httpx  # noqa: F401
        import streamlit  # noqa: F401
        import uvicorn  # noqa: F401
    except ImportError as e:
        rows.append(("dependencies", "FAIL", str(e)))
    else:
        rows.append(("dependencies", "PASS", "fastapi, streamlit, uvicorn, httpx importable"))

    try:
        import streamlit as st

        parts = st.__version__.split(".")
        major, minor = int(parts[0]), int(parts[1])
        if (major, minor) < (1, 33):
            rows.append(
                (
                    "streamlit_version",
                    "WARN",
                    f"{st.__version__} (fluxlit declares streamlit>=1.33; upgrade recommended)",
                )
            )
        else:
            rows.append(("streamlit_version", "PASS", st.__version__))
    except Exception as e:
        rows.append(("streamlit_version", "WARN", str(e)))

    if fl is not None:
        pc = load_project_config()
        host, port, _ = resolve_binding(
            cli_host=None,
            cli_port=None,
            cli_log_level=None,
            pc=pc,
            settings_gateway_host=fl.settings.gateway_host,
            settings_gateway_port=fl.settings.gateway_port,
            settings_log_level=fl.settings.log_level,
        )
        bind_host = "127.0.0.1" if host in {"0.0.0.0", ""} else host
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                s.bind((bind_host, port))
            rows.append(("gateway_bind", "PASS", f"{host}:{port} is available"))
        except OSError as e:
            rows.append(("gateway_bind", "FAIL", str(e)))

    internal = os.environ.get("FLUXLIT_INTERNAL_API_BASE", "").strip()
    if internal:
        parsed = urlparse(internal)
        if not parsed.scheme or not parsed.netloc:
            rows.append(("FLUXLIT_INTERNAL_API_BASE", "FAIL", "not a valid absolute URL"))
        elif fl is not None:
            url_path = (parsed.path or "/").rstrip("/")
            expected = fl.settings.api_mount_path.rstrip("/")
            if url_path != expected:
                rows.append(
                    (
                        "FLUXLIT_INTERNAL_API_BASE",
                        "WARN",
                        f"path {url_path!r} should match api_mount_path {expected!r}",
                    )
                )
            else:
                rows.append(("FLUXLIT_INTERNAL_API_BASE", "PASS", "set and matches api_mount_path"))
        else:
            rows.append(
                (
                    "FLUXLIT_INTERNAL_API_BASE",
                    "PASS",
                    "set (import failed; path not compared to api_mount_path)",
                )
            )
    else:
        rows.append(
            (
                "FLUXLIT_INTERNAL_API_BASE",
                "PASS",
                "unset (normal when not inside Streamlit subprocess)",
            )
        )

    return rows


@app.command()
def doctor(
    target: str | None = typer.Argument(
        default=None,
        help="Import path to your FluxLit instance (default: from fluxlit.toml or app:app).",
    ),
    warnings_only: bool = typer.Option(
        False,
        "--warnings-only",
        help="Always exit 0 (still print FAIL lines).",
    ),
) -> None:
    """Print PASS/WARN/FAIL diagnostics (imports, deps, bind, env).

    Exits with code ``1`` if any check fails, unless ``--warnings-only`` is set.
    """
    pc = load_project_config()
    resolved_target = resolve_target(target, pc)

    typer.echo("FluxLit doctor")
    typer.echo("")

    rows = _doctor_checks(resolved_target)
    for name, status, message in rows:
        typer.echo(f"{status:4}  {name}: {message}")

    typer.echo("")
    if not warnings_only and any(s == "FAIL" for _, s, _ in rows):
        raise typer.Exit(code=1)


@app.command()
def build(
    output: Annotated[
        Path | None,
        typer.Option(
            "--output",
            "-o",
            help="Directory for Dockerfile and .dockerignore (default: current directory).",
        ),
    ] = None,
    target: str | None = typer.Argument(
        default=None,
        help="Import path for CMD (default: from fluxlit.toml or app:app).",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing Dockerfile / .dockerignore.",
    ),
) -> None:
    """Emit a minimal ``Dockerfile`` and ``.dockerignore`` for container deployment.

    Refuses to overwrite existing files unless ``--force``. Adjust generated files for
    your layout (dependencies, non-root user, etc.).
    """
    pc = load_project_config()
    resolved_target = resolve_target(target, pc)
    out_dir = output or Path(".")
    out_dir.mkdir(parents=True, exist_ok=True)
    dockerfile = out_dir / "Dockerfile"
    dockerignore = out_dir / ".dockerignore"
    if not force:
        if dockerfile.exists() or dockerignore.exists():
            typer.echo(
                f"Refusing to overwrite {dockerfile} / {dockerignore} (use --force).",
                err=True,
            )
            raise typer.Exit(code=1)
    dockerfile.write_text(_dockerfile_body(resolved_target), encoding="utf-8")
    dockerignore.write_text(_dockerignore_body(), encoding="utf-8")
    typer.echo(f"Wrote {dockerfile} and {dockerignore}")


@app.command()
def new(name: str = typer.Argument(..., help="Project directory name.")) -> None:
    """Create ``<name>/app.py`` with a sample API route and Streamlit home page."""
    root = Path(name)
    if root.exists():
        typer.echo(f"Destination already exists: {root}", err=True)
        raise typer.Exit(code=1)
    root.mkdir(parents=True)
    (root / "app.py").write_text(
        '''"""FluxLit demo app."""

from fluxlit import FluxLit

app = FluxLit(title="FluxLit Demo")


@app.api.get("/users")
def users():
    return [{"name": "Ada"}]


@app.page("/")
def home(st, client):
    st.title("Dashboard")
    r = client.get("/users")
    st.write(r.json())


if __name__ == "__main__":
    import subprocess
    import sys

    subprocess.run([sys.executable, "-m", "fluxlit", "dev", "app:app"], check=True)
''',
        encoding="utf-8",
    )
    typer.echo(f"Created {root / 'app.py'} — run: cd {name} && fluxlit dev app:app")


def main() -> None:
    """Invoke the root Typer application (console script entrypoint)."""
    app()
